[package]
name = "tui"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { workspace = true }
ratatui = { workspace = true }
config = { path = "../config" }

[features]
interactive = []  
inline = []
