[package]
name = "smash-board"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"
members = ["tui", "hook"]

[features]
default = ["dep:tui", "tui?/inline"]
tui = ["dep:tui", "tui?/interactive"]
hook = ["dep:hook"]
read-config = []

[dependencies]
tui = { path = "tui", optional = true, features = ["interactive", "inline"] }
hook = { path = "hook", optional = true }
rusqlite = "0.30.0"
clap = { version = "4.5.4", features = ["derive"]}

[workspace.dependencies]
crossterm = "0.27.0" 
ratatui = "0.26.2" 
serde = { version = "1.0.201", features = ["derive"] }
toml = "0.8.12"
