[package]
name = "smash-board"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.3"
# ctrlc = "3.4.2"
rusqlite = "0.30.0"
