[workspace]
members = ["tui", "core", "hooks", "config"]
resolver = "2"

[workspace.dependencies]
crossterm = "0.27" 
ratatui = "0.26" 
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
rusqlite = "0.30"
clap = { version = "4.5.4", features = ["derive"]}
