[package]
name = "smash-board"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
tui = ["dep:ratatui", "dep:crossterm"]

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
# confy = "0.6.1"
crossterm =  {version = "0.27.0", optional = true}
ratatui =  {version = "0.26.2", optional = true}
# ctrlc = "3.4.2"
rusqlite = "0.30.0"
